### ISSUE TITLE
Social Connection sign up does not automatically assign user role

### ISSUE THREAD

**Issue by dan2014** [labs13-clone/back-end#21]
Social Connection signups do not run in webhooks. A rule must be used instead. 

https://community.auth0.com/t/post-registration-hook-not-firing-for-social-connection-user/6364/12

**Comment by WilliamConnatser** [comment]
If they don't have auth0 admin permissions, then they will automatically be assigned the user role. The code below assigns a role depending on permissions in the token on every login and registration. As long as we can add the admin:admin permission to an admin account after they register, then all they will need to do is logout and login once, and from there on out they will be automatically anointed as an admin. Or am I misunderstanding it?

From auth.js:

```//Set the users role according to the permissions property
  if (decoded.permissions.includes('admin:admin')) {

     //var used to declare role so the variable is accessible outside this if/else statement
     var role = 'admin';
  } else {
     var role = 'user';
  }

**Comment by dan2014** [comment]
This is so the backend won't have to do this. This is fixed.
